spring.application.name=gateway
server.port=8020

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Force Eureka to use IP address
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Logging for debugging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.http.server.reactive=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
# cors
