package com.example.event.Controllers;

import com.example.event.Entities.Event;
import com.example.event.Services.EventPdfService;
import com.example.event.Services.EventService;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import java.awt.Color;


import java.io.ByteArrayOutputStream;
import java.util.Date;
import java.util.List;

@RestController
@RequestMapping("/pdf")
@CrossOrigin(origins = "http://localhost:4200")
public class EventPdfRestAPI {

    @Autowired
    EventService eventService;

    @Autowired
    EventPdfService eventPdfService;

    @GetMapping("/events")
    public ResponseEntity<byte[]> generateAllEventsPdf() throws Exception {
        List<Event> events = eventService.getAllEvents();
        Document document = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PdfWriter.getInstance(document, out);
        document.open();

        // ✅ Insérer le logo Maghrebia
        try {
            String logoPath = "src/main/resources/Static/logo1.png"; // chemin relatif
            Image logo = Image.getInstance(logoPath);
            logo.scaleToFit(100, 100);
            logo.setAlignment(Image.ALIGN_CENTER);
            document.add(logo);
        } catch (Exception ex) {
            System.out.println("❌ Logo not found: " + ex.getMessage());
        }

        // 🌟 Titre principal
        Font titleFont = new Font(Font.HELVETICA, 18, Font.BOLD, Color.GREEN.darker());


        Paragraph title = new Paragraph("Events planned - Maghrebia", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        document.add(Chunk.NEWLINE); // saut de ligne

        // 🧾 Tableau
        PdfPTable table = new PdfPTable(5);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{2, 3, 3, 2, 2});
        Font headFont = new Font(Font.HELVETICA, 12, Font.BOLD, Color.WHITE);


        String[] headers = {"Title", "Date", "Venue", "Duration(hours)","Pass required"};
        for (String header : headers) {
            PdfPCell hcell = new PdfPCell(new Phrase(header, headFont));
            hcell.setBackgroundColor(Color.DARK_GRAY);

            hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(hcell);
        }

        for (Event event : events) {
            table.addCell(event.getTitle());
            table.addCell(event.getDateEvent().toString());
            table.addCell(event.getVenue());
            table.addCell(event.getDuration());
            table.addCell(event.getEventp().toString());
        }

        document.add(table);

        document.add(Chunk.NEWLINE);
        Font footerFont = new Font(Font.HELVETICA, 10, Font.ITALIC);  // Declare footerFont here
        Paragraph footer = new Paragraph("🕊️ Generated by Maghrebia - " + new Date(), footerFont);
        footer.setAlignment(Element.ALIGN_RIGHT);
        document.add(footer);

        document.close();
        HttpHeaders header = new HttpHeaders();
        header.setContentType(MediaType.APPLICATION_PDF);
        header.setContentDispositionFormData("attachment", "events_maghrebia.pdf");
        header.setCacheControl(CacheControl.noCache().getHeaderValue());

        return new ResponseEntity<>(out.toByteArray(), header, HttpStatus.OK);
    }

}
